[package]
name = "devstoreSDK"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.15", features = ["multipart", "blocking"] }
serde_json = "1.0.140"
walkdir = "2.5.0"
zip = "2.6.0"
